### ISSUE TITLE
Unable to resolve 'dot-mail' services 

### ISSUE THREAD

**Issue by gabidj** [dotkernel/dot-frontend#3]
On a fresh install

Service Manager is unable to resolve services due to missing configuration keys and aliases:

* "dot-mail.mail-service.default" 
* "dot-mail.options." (with the dot)

The `options.` dot is there reflects that the names might have been generated automatically. The absence of  alias or key name generation leads to unresolved services as `Service Manager` cannot "guess" the key's purpose.

Fix proposal: 

In /config/autoload/mail.global.php add the key 'dependencies' as follows

```php
<?php

return [
	'dependencies' => [
		'factories' => [
			Dot\Mail\Service\MailServiceInterface::class =>
                             Dot\Mail\Factory\MailServiceAbstractFactory::class,
			Dot\Mail\Options\MailOptions::class =>
                             Dot\Mail\Factory\MailOptionsAbstractFactory::class
		],
		'aliases' => [
			'dot-mail.mail-service.default' => Dot\Mail\Service\MailServiceInterface::class,
			'dot-mail.options.' => Dot\Mail\Service\MailServiceInterface::class
		],
	],
    // ... the rest of mail.global.php config
];
```

As the dependencies are strictly related to the mail service, they can be kept within mail.global.php
The key=>value pairs within `factories` and `aliases` can also be merged with the ones in dependencies.global.php

[Resolutions ZIP package](https://github.com/dotkernel/dot-frontend/files/714314/resolutions.zip)

**Comment by n3vrax** [comment]
This is because dot-mail was updated and the develop branch was prematurely merged  into master without updating frontend to reflect the changes.  You don't have to manually register the service,  as it is done through abstract factories.  I'll push an update today to fix this.

**Comment by n3vrax** [comment]
To fix this at your side, update all references to the 'dot-mail.mail-service.default'  with dot-mail.service.default

**Comment by n3vrax** [comment]
Issue was fixed in the latest update
